# Generated by Django 3.1.7 on 2021-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teams',
            field=models.ManyToManyField(null=True, to='api_core.Team'),
        ),
    ]
