# Generated by Django 3.1.7 on 2021-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_auto_20210505_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teams',
            field=models.ManyToManyField(blank=True, to='api_core.Team'),
        ),
    ]
