# Generated by Django 3.1.6 on 2021-03-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_auto_20210329_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api_core.team'),
        ),
    ]
