# Generated by Django 3.1.7 on 2021-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0003_auto_20210505_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='challenge',
            field=models.ManyToManyField(blank=True, to='api_core.Challenge'),
        ),
    ]
