# Generated by Django 3.1.6 on 2021-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0003_session_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='api_core.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teams',
            field=models.ManyToManyField(related_name='session', to='api_core.Team'),
        ),
    ]
