# Generated by Django 3.1.7 on 2021-05-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0005_auto_20210505_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthDate',
            field=models.DateField(),
        ),
    ]
