# Generated by Django 3.1.6 on 2021-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0006_auto_20210330_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proof',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
