# Generated by Django 3.1.7 on 2021-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0006_auto_20210505_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='teams',
            field=models.ManyToManyField(blank=True, to='api_core.Team'),
        ),
    ]
