# Generated by Django 3.1.7 on 2021-05-05 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0007_session_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='api_core.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teams',
            field=models.ManyToManyField(related_name='session', to='api_core.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
