# Generated by Django 3.1.6 on 2021-03-30 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0008_auto_20210330_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='validated',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
