# Generated by Django 3.1.6 on 2021-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0009_proof_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='challenge',
        ),
        migrations.AddField(
            model_name='proof',
            name='challenge',
            field=models.ManyToManyField(blank=True, null=True, to='api_core.Challenge'),
        ),
        migrations.RemoveField(
            model_name='proof',
            name='team',
        ),
        migrations.AddField(
            model_name='proof',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='api_core.Team'),
        ),
    ]
